[workspace]
members = [".", "experiments/fileio-trace-test", "experiments/fileio-trace-test/fileio-events-macro", "experiments/fileio-flag-discovery", "experiments/perf-flt-compare", "experiments/kernel-fileio-example"]
resolver = "3"

[package]
name = "fileiolog"
version = "0.1.0"
edition = "2024"

[dependencies]
ferrisetw = { git = "https://github.com/n4r1b/ferrisetw", rev = "22caa099ea57a295b0e4cf91a741771bfde6bc0d", features = ["time_rs"] }
ringbuf = "0.5.0"
phf = { version = "0.14.0", features = ["macros"] }
env_logger = "0.11.11"
log = "0.4.33"
etw-macros = { path = "etw-macros" }

# Must match ferrisetw's internal windows crate version exactly (0.61.3).
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Etw",
] }
serde = "1.0.228"
time = "0.3.53"

[dev-dependencies]
trybuild = "1.0.117"
